# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1198ffa54d6d2f75f9d75bddd9cd0d8bac07a7f1dd738479b14b5fd19ff5b78443e0fc7551cce8b947c339065a1592925d10a24a3f99c3a05b26a870bc7fabbc

test:
  secret_key_base: 3de287d23090f93d91a0e28963474a82593ce0b9d3a1871352724c98fd42945e132c1ab782f1389d44060c7f28dc7de8ec682916bd799232ef805eecd0621cce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
