class SkillSeed
  def initialize
  end
  def self.dev_skills
    dev_skills = [
    ".NET ",
    "4D",
    "Active Directory",
    "Adobe Air",
    "Adobe Lightroom",
    "Agile Development",
    "AJAX",
    "Alibaba",
    "Amazon Web Services",
    "AMQP",
    "Analytics",
    "Android Wear SDK",
    "Angular.js",
    "Apache",
    "Apache Solr",
    "Apple Safari",
    "Argus Monitoring Software",
    "AS400 & iSeries",
    "ASP",
    "ASP.NET",
    "Assembly",
    "Asterisk PBX",
    "Augmented Reality",
    "AutoHotkey",
    "Azure",
    "backbone.js",
    "Balsamiq",
    "Big Data",
    "BigCommerce",
    "Binary Analysis",
    "Bitcoin",
    "Biztalk",
    "Blog Install",
    "Bluetooth Low Energy",
    "BMC Remedy",
    "Boonex Dolphin",
    "Bower",
    "BSD",
    "Business Catalyst",
    "C Programming",
    "C# Programming",
    "C++ Programming",
    "CakePHP",
    "Call Control XML",
    "CasperJS",
    "Cassandra",
    "Chef Configuration Management",
    "Chordiant",
    "Chrome OS",
    "Cisco",
    "Cloud Computing",
    "CMS",
    "COBOL",
    "Cocoa",
    "Codeigniter",
    "Cold Fusion",
    "Computer Graphics",
    "Computer Security",
    "CRE Loaded",
    "CS-Cart",
    "CubeCart",
    "CUDA",
    "D3.js",
    "Dart",
    "Data Warehousing",
    "Database Administration",
    "Database Development",
    "Database Programming",
    "DDS",
    "Debian",
    "Debugging",
    "Delphi",
    "Django",
    "DNS",
    "DOS",
    "DotNetNuke",
    "Drupal",
    "Dynamics",
    "eCommerce",
    "edX",
    "Elasticsearch",
    "eLearning",
    "Electronic Forms",
    "Embedded Software",
    "Ember.js",
    "Erlang",
    "Express JS",
    "Expression Engine",
    "Face Recognition",
    "FileMaker",
    "Firefox",
    "Fortran",
    "Forum Software",
    "FreelancerAPI",
    "Game Consoles",
    "Game Design",
    "Game Development",
    "GameSalad",
    "Gamification",
    "Git",
    "Golang",
    "Google Analytics",
    "Google App Engine",
    "Google Cardboard",
    "Google Chrome",
    "Google Earth",
    "Google Maps API",
    "Google Plus",
    "Google Web Toolkit",
    "Google Webmaster Tools",
    "Google Website Optimizer",
    "GoPro",
    "GPGPU",
    "Grease Monkey",
    "Growth Hacking",
    "Grunt",
    "Hadoop",
    "Haskell",
    "HBase",
    "Heroku",
    "Hive",
    "HomeKit",
    "HP Openview",
    "HTML",
    "HTML5",
    "iBeacon",
    "IBM Tivoli",
    "IBM Websphere Transformation Tool",
    "IIS",
    "Instagram",
    "Internet Security",
    "Interspire",
    "ITIL",
    "J2EE",
    "Jabber",
    "Java",
    "JavaFX",
    "Javascript",
    "Joomla",
    "jQuery / Prototype",
    "JSP",
    "Kinect",
    "Knockout.js",
    "LabVIEW",
    "Laravel",
    "Leap Motion SDK",
    "LESS/Sass/SCSS",
    "Link Building",
    "Linkedin",
    "Linux",
    "Lisp",
    "Lotus Notes",
    "Mac OS",
    "Magento",
    "Magic Leap",
    "Map Reduce",
    "MariaDB",
    "Metatrader",
    "Microsoft",
    "Microsoft Access",
    "Microsoft Exchange",
    "Microsoft Expression",
    "Microsoft Hololens",
    "Microsoft SQL Server",
    "MMORPG",
    "Mobile App Testing",
    "MODx",
    "MonetDB",
    "Moodle",
    "MQTT",
    "MVC",
    "MySpace",
    "MySQL",
    "Network Administration",
    "Nginx",
    "Ning",
    "node.js",
    "NoSQL Couch & Mongo",
    "Objective C",
    "OCR",
    "Oculus Mobile SDK",
    "Open Cart",
    "OpenBravo",
    "OpenCL",
    "OpenGL",
    "OpenVMS",
    "Oracle",
    "OSCommerce",
    "Papiamento",
    "Parallax Scrolling",
    "Parallels Automation",
    "Parallels Desktop",
    "Pattern Matching",
    "Paypal API",
    "PencilBlue CMS",
    "Pentaho",
    "Perl",
    "PhoneGap",
    "Photoshop Coding",
    "PHP",
    "PICK Multivalue DB",
    "Pinterest",
    "Plesk",
    "Plugin",
    "PostgreSQL",
    "Prestashop",
    "Prolog",
    "Protoshare",
    "Puppet",
    "Python",
    "QlikView",
    "Qualtrics Survey Platform",
    "QuickBase",
    "R Programming Language",
    "React.js",
    "REALbasic",
    "Red Hat",
    "Redis",
    "RESTful",
    "Rocket Engine",
    "Ruby",
    "Ruby on Rails",
    "Salesforce App Development",
    "Samsung Accessory SDK",
    "SAP",
    "Scala",
    "Scheme",
    "Script Install",
    "Scrum",
    "Scrum Development",
    "Sencha / YahooUI",
    "SEO",
    "Sharepoint",
    "Shell Script",
    "Shopify",
    "Shopping Carts",
    "Siebel",
    "Silverlight",
    "Smarty PHP",
    "Snapchat",
    "Social Engine",
    "Social Networking",
    "Socket IO",
    "Software Architecture",
    "Software Development",
    "Software Testing",
    "Solaris",
    "Spark",
    "Sphinx",
    "SPSS Statistics",
    "SQL",
    "SQLite",
    "Squarespace",
    "Steam API",
    "Stripe",
    "SugarCRM",
    "Swift",
    "Symfony PHP",
    "System Admin",
    "TaoBao API",
    "TestStand",
    "Tizen SDK for Wearables",
    "Tumblr",
    "Twitter",
    "TYPO3",
    "Ubuntu",
    "Umbraco",
    "UML Design",
    "Unity 3D",
    "UNIX",
    "Usability Testing",
    "User Interface / IA",
    "VB.NET",
    "vBulletin",
    "VertexFX",
    "Virtual Worlds",
    "Virtuemart",
    "Virtuozzo",
    "Visual Basic",
    "Visual Basic for Apps",
    "Visual Foxpro",
    "VMware",
    "VoiceXML",
    "VoIP",
    "Volusion",
    "VPS",
    "vTiger",
    "Vuforia",
    "WatchKit",
    "Web Hosting",
    "Web Scraping",
    "Web Security",
    "Web Services",
    "webMethods",
    "Website Management",
    "Website Testing",
    "Weebly",
    "WHMCS",
    "Windows 8",
    "Windows API",
    "Windows Desktop",
    "Windows Server",
    "Wix",
    "Wordpress",
    "WPF",
    "Wufoo",
    "x86/x64 Assembler",
    "XML",
    "XMPP",
    "Xoops",
    "XQuery",
    "XSLT",
    "Yarn",
    "Yii",
    "YouTube",
    "Zen Cart",
    "Zend",
    "Zendesk",
    "Zoho"]
    dev_skills
  end

  def self.mobile_skills
    mobile_skills = [
    "Amazon Fire",
    "Amazon Kindle",
    "Android",
    "Android Honeycomb",
    "Appcelerator Titanium",
    "Apple Watch",
    "Blackberry",
    "Geolocation",
    "iPad",
    "iPhone",
    "J2ME",
    "Metro",
    "Mobile Phone",
    "Nokia",
    "Palm",
    "Samsung",
    "Symbian",
    "WebOS",
    "Windows CE",
    "Windows Mobile",
    "Windows Phone"]
    mobile_skills
  end

  def self.writing_skills
    writing_skills = [
    "Academic Writing",
    "Article Rewriting",
    "Articles",
    "Blog",
    "Book Writing",
    "Business Writing",
    "Cartography & Maps",
    "Catch Phrases",
    "Communications",
    "Content Writing",
    "Copy Typing",
    "Copywriting",
    "Creative Writing",
    "eBooks",
    "Editing",
    "Fiction",
    "Financial Research",
    "Forum Posting",
    "Ghostwriting",
    "Grant Writing",
    "LaTeX",
    "Medical Writing",
    "Newsletters",
    "Online Writing",
    "PDF",
    "Poetry",
    "Powerpoint",
    "Press Releases",
    "Product Descriptions",
    "Proofreading",
    "Proposal/Bid Writing",
    "Publishing",
    "Report Writing",
    "Research",
    "Resumes",
    "Reviews",
    "Screenwriting",
    "Short Stories",
    "Slogans",
    "Speech Writing",
    "Technical Writing",
    "Translation",
    "Travel Writing",
    "WIKI",
    "Wikipedia",
    "Word Processing"]
    writing_skills
  end

  def self.design_media_and_architecture_skills
    design_media_and_architecture_skills = [
    "360-degree video",
    "3D Animation",
    "3D Design",
    "3D Modelling",
    "3D Rendering",
    "3ds Max",
    "ActionScript",
    "Adobe Dreamweaver",
    "Adobe Flash",
    "Adobe InDesign",
    "Adobe LiveCycle Designer",
    "Advertisement Design",
    "After Effects",
    "Animation",
    "Apple Compressor",
    "Apple Logic Pro",
    "Apple Motion",
    "Arts & Crafts",
    "Audio Production",
    "Audio Services",
    "Autodesk Inventor",
    "Autodesk Revit",
    "Banner Design",
    "Blog Design",
    "Bootstrap",
    "Brochure Design",
    "Building Architecture",
    "Business Cards",
    "Capture NX2",
    "Caricature & Cartoons",
    "CGI",
    "Cinema 4D",
    "Commercials",
    "Concept Design",
    "Corporate Identity",
    "Covers & Packaging",
    "Creative Design",
    "CSS",
    "Fashion Design",
    "Fashion Modeling",
    "Final Cut Pro",
    "Finale / Sibelius",
    "Flash 3D",
    "Flex",
    "Flyer Design",
    "Format & Layout",
    "Furniture Design",
    "GarageBand",
    "Google SketchUp",
    "Graphic Design",
    "Icon Design",
    "Illustration",
    "Illustrator",
    "iMovie",
    "Industrial Design",
    "Infographics",
    "Interior Design",
    "Invitation Design",
    "JDF",
    "Label Design",
    "Landing Pages",
    "Logo Design",
    "Makerbot",
    "Maya",
    "Motion Graphics",
    "Music",
    "Package Design",
    "Photo Editing",
    "Photography",
    "Photoshop",
    "Photoshop Design",
    "Post-Production",
    "Poster Design",
    "Pre-production",
    "Presentations",
    "Prezi",
    "Print",
    "PSD to HTML",
    "PSD2CMS",
    "QuarkXPress",
    "RWD",
    "Shopify Templates",
    "Sound Design",
    "Stationery Design",
    "Sticker Design",
    "T-Shirts",
    "Tattoo Design",
    "Templates",
    "Typography",
    "User Experience Design",
    "Video Broadcasting",
    "Video Editing",
    "Video Production",
    "Video Services",
    "Videography",
    "Visual Arts",
    "Voice Talent",
    "Website Design",
    "Word",
    "Yahoo! Store Design"]
    design_media_and_architecture_skills
  end
  def self.data_entry_skills
    data_entry_skills = [
    "Article Submission",
    "Bookkeeping",
    "BPO",
    "Call Center",
    "Customer Service",
    "Customer Support",
    "Data Entry",
    "Data Processing",
    "Desktop Support",
    "Email Handling",
    "Excel",
    "General Office",
    "Helpdesk",
    "Investment Research",
    "Microsoft Office",
    "Microsoft Outlook",
    "Order Processing",
    "Phone Support",
    "Procurement",
    "Technical Support",
    "Telephone Handling",
    "Time Management",
    "Transcription",
    "Video Upload",
    "Virtual Assistant",
    "Web Search"]
    data_entry_skills
  end
  def self.engineering_and_science_skills
    engineering_and_science_skills = [
    "Aeronautical Engineering",
    "Aerospace Engineering",
    "Algorithm",
    "Arduino",
    "Astrophysics",
    "AutoCAD",
    "Biology",
    "Biotechnology",
    "Broadcast Engineering",
    "CAD/CAM",
    "Chemical Engineering",
    "Circuit Design",
    "Civil Engineering",
    "Clean Technology",
    "Climate Sciences",
    "Construction Monitoring",
    "Cryptography",
    "Data Mining",
    "Data Science",
    "Digital Design",
    "Drones",
    "Electrical Engineering",
    "Electronics",
    "Engineering",
    "Engineering Drawing",
    "Finite Element Analysis",
    "FPGA",
    "Genetic Engineering",
    "Geology",
    "Geospatial",
    "GPS",
    "Home Design",
    "Human Sciences",
    "Imaging",
    "Industrial Engineering",
    "Instrumentation",
    "Linear Programming",
    "Machine Learning",
    "Manufacturing Design",
    "Materials Engineering",
    "Mathematics",
    "Matlab & Mathematica",
    "Mechanical Engineering",
    "Mechatronics",
    "Medical",
    "Microbiology",
    "Microcontroller",
    "Microstation",
    "Mining Engineering",
    "Nanotechnology",
    "Natural Language",
    "PCB Layout",
    "Petroleum Engineering",
    "Physics",
    "PLC & SCADA",
    "Product Management",
    "Project Scheduling",
    "Quantum",
    "Remote Sensing",
    "Renewable Energy Design",
    "Robotics",
    "RTOS",
    "Scientific Research",
    "Solidworks",
    "Statistical Analysis",
    "Statistics",
    "Structural Engineering",
    "Surfboard Design",
    "Telecommunications Engineering",
    "Textile Engineering",
    "Verilog / VHDL",
    "Wireless",
    "Wolfram"]
    engineering_and_science_skills
  end

  def self.manufacturing_skills
    manufacturing_skills = [
    "3D Printing",
    "Buyer Sourcing",
    "Logistics & Shipping",
    "Manufacturing",
    "Product Design",
    "Product Sourcing",
    "Supplier Sourcing"]
    manufacturing_skills
  end

  def self.sales_skills
    sales_skills = [
    "Ad Planning & Buying",
    "Advertising",
    "Affiliate Marketing",
    "Airbnb",
    "Branding",
    "Bulk Marketing",
    "Classifieds Posting",
    "Conversion Rate Optimisation",
    "CRM",
    "eBay",
    "Email Marketing",
    "Etsy",
    "Facebook Marketing",
    "Google Adsense",
    "Google Adwords",
    "Internet Marketing",
    "Internet Research",
    "Leads",
    "Mailchimp",
    "Market Research",
    "Marketing",
    "MLM",
    "Periscope",
    "Sales",
    "Search Engine Marketing",
    "Social Media Marketing",
    "Telemarketing",
    "Viral Marketing",
    "WooCommerce"]
    sales_skills
  end

  def self.business_legal_skills
    business_legal_skills = [
    "Accounting",
    "Audit",
    "Business Analysis",
    "Business Plans",
    "Compliance",
    "Contracts",
    "Employment Law",
    "Entrepreneurship",
    "ERP",
    "Event Planning",
    "Finance",
    "Financial Analysis",
    "Fundraising",
    "Human Resources",
    "Inventory Management",
    "ISO9001",
    "Legal",
    "Legal Research",
    "Legal Writing",
    "Management",
    "MYOB",
    "Patents",
    "Payroll",
    "PeopleSoft",
    "Personal Development",
    "Project Management",
    "Property Development",
    "Property Law",
    "Property Management",
    "Public Relations",
    "Quickbooks & Quicken",
    "Recruitment",
    "Risk Management",
    "Salesforce.com",
    "SAS",
    "Startups",
    "Tax",
    "Tax Law",
    "Visa / Immigration",
    "Xero"]
    business_legal_skills
  end

  def self.language_skills
    language_skills = [
    "Afrikaans",
    "Albanian",
    "Arabic",
    "Basque",
    "Bengali",
    "Bosnian",
    "Bulgarian",
    "Catalan",
    "Croatian",
    "Czech",
    "Danish",
    "Dari",
    "Dutch",
    "English",
    "English",
    "English Grammar",
    "English Spelling",
    "Estonian",
    "Filipino",
    "Finnish",
    "French",
    "French",
    "German",
    "Greek",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Indonesian",
    "Italian",
    "Japanese",
    "Kannada",
    "Korean",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Malay",
    "Malayalam",
    "Maltese",
    "Norwegian",
    "Polish",
    "Portuguese",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Serbian",
    "Simplified Chinese",
    "Slovakian",
    "Slovenian",
    "Spanish",
    "Spanish",
    "Swedish",
    "Tamil",
    "Telugu",
    "Thai",
    "Traditional Chinese",
    "Traditional Chinese",
    "Turkish",
    "Ukranian",
    "Urdu",
    "Vietnamese",
    "Welsh"]
    language_skills
  end

  def self.handy_work_skills
    handy_work_skills = [
    "Air Conditioning",
    "Antenna Services",
    "Appliance Installation",
    "Appliance Repair",
    "Asbestos Removal",
    "Asphalt",
    "Attic Access Ladders",
    "Awnings",
    "Balustrading",
    "Bamboo Flooring",
    "Bathroom",
    "Brackets",
    "Bricklaying",
    "Building",
    "Building Certifiers",
    "Building Consultants",
    "Building Designer",
    "Building Surveyors",
    "Carpentry",
    "Carpet Repair & Laying",
    "Carports",
    "Carwashing",
    "Ceilings",
    "Cement Bonding Agents",
    "Cleaning Carpet",
    "Cleaning Domestic",
    "Cleaning Upholstery",
    "Clothesline",
    "Coating Materials",
    "Columns",
    "Commercial Cleaning",
    "Computer Help",
    "Concreting",
    "Cooking / Baking",
    "Courses",
    "Damp Proofing",
    "Decking",
    "Decoration",
    "Delivery",
    "Demolition",
    "Disposals",
    "Drafting",
    "Drains",
    "Electricians",
    "Equipment Hire",
    "Event Staffing",
    "Excavation",
    "Extensions & Additions",
    "Fencing",
    "Feng Shui",
    "Financial Planning",
    "Floor Coatings",
    "Flooring",
    "Flyscreens",
    "Food Takeaway",
    "Frames & Trusses",
    "Furniture Assembly",
    "Gardening",
    "Gas Fitting",
    "Glass / Mirror & Glazing",
    "Guttering",
    "Handyman",
    "Heating Systems",
    "Home Automation",
    "Home Organization",
    "Hot Water",
    "House Cleaning",
    "Housework ",
    "IKEA Installation",
    "Inspections",
    "Installation",
    "Interiors",
    "Kitchen",
    "Landscaping",
    "Landscaping & Gardening",
    "Laundry and Ironing",
    "Lawn Mowing",
    "Lighting",
    "Locksmith",
    "Millwork",
    "Mortgage Brokering",
    "Moving",
    "Packing & Shipping",
    "Painting",
    "Pavement",
    "Pest Control",
    "Pet Sitting",
    "Pickup",
    "Piping",
    "Plumbing",
    "Removalist",
    "Roofing",
    "Sculpturing",
    "Sewing",
    "Shopping",
    "Tiling",
    "Workshops",
    "Yard Work & Removal"]
    handy_work_skills
  end

  def self.other_skills
    other_skills = [
    "Anything Goes",
    "Automotive",
    "Brain Storming",
    "Business Coaching",
    "Christmas",
    "Cooking & Recipes",
    "Dating",
    "Education & Tutoring",
    "Energy",
    "Financial Markets",
    "Flashmob",
    "Freelance",
    "Genealogy",
    "Health",
    "History",
    "Insurance",
    "Jewellery",
    "Life Coaching",
    "Nutrition",
    "Pattern Making",
    "Psychology",
    "Real Estate",
    "Sports",
    "Test Automation",
    "Testing / QA",
    "Training",
    "Troubleshooting",
    "Valuation & Appraisal",
    "Weddings"]
    other_skills
  end

end
